name: Tests (PR)

# 1. ТРИГГЕР: когда запускать?
on:
  pull_request:
    branches: [ main ]
  schedule:
    # Запуск в 0-ю минуту каждого часа (UTC)
    - cron: '0 * * * *'
  # Позволяет также нажимать кнопку "Run workflow" вручную из интерфейса
  workflow_dispatch:

# 2. ЗАДАЧИ: что именно делать?
jobs:
  smoke-tests:
    name: Run Test Suite
    runs-on: ubuntu-latest # GitHub выделит чистую виртуальную машину на Linux

    steps:
      # Шаг 1: Скачиваем код из ветки PR на виртуальную машину
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Шаг 2: Устанавливаем Java 17 и настраиваем кэширование зависимостей Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven' # GitHub сохранит зависимости, чтобы не качать интернет заново при каждом запуске

      # Шаг 3: Запускаем сьют тестов
      - name: Execute TestNG Smoke Suite
        run: xvfb-run mvn test -DsuiteXmlFile=src/test/resources/testng.xml