name: Tests (PR)


on:
  pull_request:
    branches: [ main ]
  schedule:

    - cron: '15 9,18 * * *'

  workflow_dispatch:

# 2.
jobs:
  smoke-tests:
    name: Run Test Suite
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Скачиваем код из ветки PR на виртуальную машину
      - name: Checkout repository code
        uses: actions/checkout@v4

      # docker appendix

      - name: Build Docker image
        run: docker build -t jobich-tests .

      - name: Run tests in container
        run: |
          docker run --rm -v ${{ github.workspace }}/target:/app/target jobich-tests
          sudo chown -R $(id -u):$(id -g) target

      # 4
      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy report history
        if: always()
        run: |
          mkdir -p target/allure-results/history
          cp -r gh-pages/history/* target/allure-results/history/ 2>/dev/null || true

      - name: Install Allure commandline
        if: always()
        run: npm install -g allure-commandline --save-dev

      - name: Generate Allure report
        if: always()
        run: allure generate target/allure-results --clean -o allure-report

      - name: Publish report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report